In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds = pd.read_csv('data.csv')

In [3]:
ds.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
ds['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [6]:
sorted(ds['R&D Spend'].unique())  # sorting and giving data of speific column

[0.0,
 542.05,
 1000.23,
 1315.46,
 15505.73,
 20229.59,
 22177.74,
 23640.93,
 27892.92,
 28663.76,
 28754.33,
 38558.51,
 44069.95,
 46014.02,
 46426.07,
 55493.95,
 61136.38,
 61994.48,
 63408.86,
 64664.71,
 65605.48,
 66051.52,
 67532.53,
 72107.6,
 73994.56,
 75328.87,
 76253.86,
 77044.01,
 78013.11,
 78389.47,
 86419.7,
 91749.16,
 91992.39,
 93863.75,
 94657.16,
 100671.96,
 101913.08,
 114523.61,
 119943.24,
 120542.52,
 123334.88,
 130298.13,
 131876.9,
 134615.46,
 142107.34,
 144372.41,
 153441.51,
 162597.7,
 165349.2]

In [7]:
ds['State'].value_counts()   # counting the data of rows by specific rowed values

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [8]:
 #using onehotencoder to make state column to numeric
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False)
encoded_data = ohe.fit_transform(ds[['State']])

column_names = ohe.get_feature_names_out(['State'])
encoded_df = pd.DataFrame(data = encoded_data, columns = column_names)
ds = pd.concat([ds, encoded_df], axis = 1)

In [9]:
ds = ds.drop(columns = ['State'])

In [10]:
# dividing data
X = ds[['R&D Spend', 'Administration', 'Marketing Spend','State_California', 'State_Florida', 'State_New York']]
y = ds[['Profit']]

In [11]:
# dividing data for training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [12]:
# Lets create model and train
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [13]:
data = [[100000, 100000, 100000, 1, 0, 0]]
myinput = pd.DataFrame(columns = X.columns, data = data)
myinput

R&D Spend  Administration  Marketing Spend  State_California  \
0     100000          100000           100000                 1   

   State_Florida  State_New York  
0              0               0

In [14]:
reg.predict(myinput)

array([[127999.26156755]])

In [15]:
reg.predict(X_test)

array([[101475.55240111],
       [133287.417583  ],
       [132546.1614474 ],
       [ 72702.7136192 ],
       [178346.51727008]])

In [16]:
y_test

Profit
28  103282.38
11  144259.40
10  146121.95
41   77798.83
2   191050.39

In [17]:
res = reg.predict(X_test)

In [18]:
# To find accuracy of preiction of model training
# more the r2_score better the result

from sklearn.metrics import r2_score
r2_score(res, y_test)

0.9207638669814051

In [19]:
# finding result for my inputs

data = [[0, 0, 0, 1, 0, 0]]
myinput = pd.DataFrame(columns = X.columns, data = data)
myinput
res = reg.predict(myinput)
res

array([[46375.58749716]])